name: Build & Push Frigate‑NFS to Docker Hub

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: frigate-nfs-wrapper

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # # ───── OPTIONAL: trigger Portainer redeploy ─────
      # - name: Redeploy stack in Portainer
      #   if: success() # only if build+push succeeded
      #   env:
      #     PORTAINER_URL: ${{ secrets.PORTAINER_URL }} # e.g. https://portainer.mydomain.com
      #     STACK_ID: ${{ secrets.PORTAINER_STACK_ID }} # numeric ID shown in URL (/stack/5)
      #     API_KEY: ${{ secrets.PORTAINER_API_KEY }} # generate in Portainer > My account > API keys
      #   run: |
      #     curl -s -X POST \
      #       -H "X-API-Key: $API_KEY" \
      #       "$PORTAINER_URL/api/stacks/$STACK_ID/stack/redeploy?pullImage=true"
